import React from "react";
import Head from 'next/head';



export default function App() {

  return (

<div className="App">  

  <Head>
  <meta charset="utf-8"></meta>
  <title>Mentions légales</title>
  <meta content="Mentions légales" property="og:title"></meta>
  <meta content="Mentions légales" property="twitter:title"></meta>
  <meta content="width=device-width, initial-scale=1" name="viewport"></meta>
  <link href="images/favicon.jpg" rel="shortcut icon" type="image/x-icon"></link>
  <link href="images/webclip.jpg" rel="apple-touch-icon"></link>

  </Head>

<body class="body-4">
<div class="legal-background">
 <h1 class="heading-42"><strong>Mentions légales et politique de confidentialité</strong></h1>
  <p class="paragraph-30">La société KERU PROJECT, soucieuse des droits des individus, notamment au regard des traitements automatisés et dans une volonté de transparence avec ses clients, a mis en place une politique reprenant l’ ensemble de ces traitements, des finalités poursuivies par ces derniers ainsi que des moyens d’actions à la disposition des individus afin qu’ils puissent au mieux exercer leurs droits.Pour toute information complémentaire sur la protection des données personnelles, nous vous invitons à consulter le site : https://www.cnil.fr/</p>
  <p class="paragraph-36">La poursuite de la navigation sur ce site vaut acceptation sans réserve des dispositions et conditions d&#x27;utilisation qui suivent.<br></br>La version actuellement en ligne de ces conditions d&#x27;utilisation est la seule opposable pendant toute la durée d&#x27;utilisation du site et jusqu&#x27;à ce qu&#x27;une nouvelle version la remplace.</p>
  <h4 class="heading-43"><strong class="bold-text-10">Article 1 - Mentions légales</strong></h4>
  <p class="paragraph-31">Le présent site, accessible à l’URL www.keruproject.org (le « Site »), est édité par: Hélène Quintin</p>
  <h5 class="heading-50">1.1 Site (ci-après « le site ») :</h5>
  <p class="paragraph-32">KERU PROJECT</p>
  <h5 class="heading-50">1.2 Éditeur (ci-après « l&#x27;éditeur ») :</h5>
  <p class="paragraph-32">KERU PROJECT SAS au capital de 100 €<br></br>dont le siège social est situé : 1 Faubourg Saint-Armel 44350 GUERANDE représentée par Hélène Quintin, en sa qualité de Président<br></br>immatriculée au RCS de Saint-Nazaire<br></br>SIREN : 917 911 075<br></br>adresse mail : hello@kerudao.org<br></br>directeur de la publication : Hélène Quintin<br></br></p>
  <h5 class="heading-50">1.3 Hébergeur (ci-après « l&#x27;hébergeur ») :<br></br></h5>
  <p class="paragraph-32">KERU PROJECT est hébergé par Hostinger, dont le siège social est situé Jonavos g. 60C, 44192 Lituanie.<br></br></p>
  <h4 class="heading-43"><strong class="bold-text-10">Article 2 - Accès au site</strong></h4>
  <p class="paragraph-32">L&#x27;accès au site et son utilisation sont réservés à un usage strictement personnel. Vous vous engagez à ne pasutiliser ce site et les informations ou données qui y figurent à des fins commerciales, politiques, publicitaires et pour toute forme de sollicitation commerciale et notamment l&#x27;envoi de courriers électroniques non sollicités.<br></br></p>
  <h4 class="heading-43"><strong class="bold-text-10">Article 3 - Contenu du site</strong></h4>
  <p class="paragraph-32">Toutes les marques, photographies, textes, commentaires, illustrations, images animées ou non, séquencesvidéo, sons, ainsi que toutes les applications informatiques qui pourraient être utilisées pour faire fonctionner ce site et plus généralement tous les éléments reproduits ou utilisés sur le site sont protégés par les lois en vigueur au titre de la propriété intellectuelle. Ils sont la propriété pleine et entière de l&#x27;éditeur ou de ses partenaires. Toute reproduction, représentation, utilisation ou adaptation, sous quelque forme que ce soit, de tout ou partie de ces éléments, y compris les applications informatiques, sans l&#x27;accord préalable et écrit de l&#x27;éditeur, sont strictement interdites. Le fait pour l&#x27;éditeur de ne pas engager de procédure dès la prise de connaissance de ces utilisations non autorisées ne vaut pas acceptation desdites utilisations et renonciation aux poursuites.</p>
  <h4 class="heading-43"><strong class="bold-text-10">Article 4 - Gestion du site</strong></h4>
  <p class="paragraph-32">Pour la bonne gestion du site, l&#x27;éditeur pourra à tout moment :- suspendre, interrompre ou limiter l&#x27;accès à tout ou partie du site, réserver l&#x27;accès au site, ou à certaines parties du site, à une catégorie déterminée d&#x27;internautes ;<br></br>- supprimer toute information pouvant en perturber le fonctionnement ou entrant en contravention avec les lois nationales ou internationales ;<br></br>- suspendre le site afin de procéder à des mises à jour.<br></br></p>
  <h4 class="heading-43"><strong class="bold-text-10">Article 5 - Responsabilités</strong></h4>
  <p class="paragraph-32">La responsabilité de l&#x27;éditeur ne peut être engagée en cas de défaillance, panne, difficulté ou interruption defonctionnement, empêchant l&#x27;accès au site ou à une de ses fonctionnalités.<br></br>Le matériel de connexion au site que vous utilisez est sous votre entière responsabilité. Vous devez prendre toutes les mesures appropriées pour protéger votre matériel et vos propres données notamment d&#x27;attaques virales par Internet. Vous êtes par ailleurs seul responsable des sites et données que vous consultez.L&#x27;éditeur ne pourra être tenu responsable en cas de poursuites judiciaires à votre encontre : - du fait de l&#x27;usage du site ou de tout service accessible via Internet ;<br></br>- du fait du non-respect par vous des présentes conditions générales.L&#x27;éditeur n&#x27;est pas responsable des dommages causés à vous-même, à des tiers et/ou à votre équipement du fait de votre connexion ou de votre utilisation du site et vous renoncez à toute action contre lui de ce fait.<br></br>Si l&#x27;éditeur venait à faire l&#x27;objet d&#x27;une procédure amiable ou judiciaire en raison de votre utilisation du site, il pourra se retourner contre vous pour obtenir l&#x27;indemnisation de tous les préjudices, sommes, condamnations et frais qui pourraient découler de cette procédure.<br></br></p>
  <h4 class="heading-43"><strong class="bold-text-10">Article 6 - Liens hypertextes</strong></h4>
  <p class="paragraph-32">La mise en place par les utilisateurs de tous liens hypertextes vers tout ou partie du site est strictement interdite, sauf autorisation préalable et écrite de l&#x27;éditeur.<br></br>L&#x27;éditeur est libre de refuser cette autorisation sans avoir à justifier de quelque manière que ce soit sa décision. Dans le cas où l&#x27;éditeur accorderait son autorisation, celle-ci n&#x27;est dans tous les cas que temporaire et pourra être retirée à tout moment, sans obligation de justification à la charge de l&#x27;éditeur.Toute information accessible via un lien vers d&#x27;autres sites n&#x27;est pas publiée par l&#x27;éditeur. L&#x27;éditeur ne dispose d&#x27;aucun droit sur le contenu présent dans ledit lien.<br></br></p>
  <h4 class="heading-43"><strong class="bold-text-10">Article 7 - Collecte et protection des données</strong></h4>
  <p class="paragraph-32">Vos données sont collectées par la société KERU PROJECT.Une donnée à caractère personnel désigne toute information concernant une personne physique identifiée ou identifiable (personne concernée) ; est réputée identifiable une personne qui peut être identifiée, directement ou indirectement, notamment par référence à un nom, un numéro d&#x27;identification ou à un ou plusieurs éléments spécifiques, propres à son identité physique, physiologique, génétique, psychique, économique, culturelle ou sociale.Les informations personnelles pouvant être recueillies sur le site sont principalement utilisées par l&#x27;éditeur pour la gestion des relations avec vous, et le cas échéant pour le traitement de vos commandes.Les données personnelles collectées sont les suivantes :<br></br></p>
  <h4 class="heading-43"><strong class="bold-text-10">Article 8 - Droit d’accès, de rectification et de déréférencement de vos données</strong></h4>
  <p class="paragraph-32">En application de la réglementation applicable aux données à caractère personnel, les utilisateurs disposent des droits suivants : le droit d’accès : ils peuvent exercer leur droit d&#x27;accès, pour connaître les données personnelles les concernant, en écrivant à l&#x27;adresse électronique ci-dessous mentionnée. Dans ce cas, avant la mise en œuvre de ce droit, la Plateforme peut demander une preuve de l&#x27;identité de l&#x27;utilisateur afin d&#x27;en vérifier l&#x27;exactitude ; le droit de rectification : si les données à caractère personnel détenues par la Plateforme sont inexactes, ils peuvent demander la mise à jour des informations ;le droit de suppression des données : les utilisateurs peuvent demander la suppression de leurs données à caractère personnel, conformément aux lois applicables en matière de protection des données ;le droit à la limitation du traitement : les utilisateurs peuvent de demander à la Plateforme de limiter le traitement des données personnelles conformément aux hypothèses prévues par le RGPD ;le droit de s’opposer au traitement des données : les utilisateurs peuvent s’opposer à ce que leurs données soient traitées conformément aux hypothèses prévues par le RGPD ;le droit à la portabilité : ils peuvent réclamer que la Plateforme leur remette les données personnelles qu&#x27;ils ont fournies pour les transmettre à une nouvelle Plateforme.Vous pouvez exercer ce droit en nous contactant, à l’adresse suivante : 1 Faubourg Saint-Armel 44350 GUERANDE .Ou par email, à l’adresse : hello@kerudao.org Toute demande doit être accompagnée de la photocopie d’un titre d’identité en cours de validité signé et faire mention de l’adresse à laquelle l&#x27;éditeur pourra contacter le demandeur. La réponse sera adressée dans le mois suivant la réception de la demande. Ce délai d&#x27;un mois peut être prolongé de deux mois si la complexité de la demande et/ou le nombre de demandes l&#x27;exigent. De plus, et depuis la loi n°2016-1321 du 7 octobre 2016, les personnes qui le souhaitent, ont la possibilité d’ organiser le sort de leurs données après leur décès. Pour plus d’information sur le sujet, vous pouvez consulter le site Internet de la CNIL : https://www.cnil.fr/.Les utilisateurs peuvent aussi introduire une réclamation auprès de la CNIL sur le site de la CNIL : https://www.cnil.fr. Nous vous recommandons de nous contacter dans un premier temps avant de déposer une réclamation auprès de la CNIL, car nous sommes à votre entière disposition pour régler votre problème.</p>
  <h4 class="heading-43"><strong class="bold-text-10">Article 9 - Utilisation des données</strong></h4>
  <p class="paragraph-32">Les données personnelles collectées auprès des utilisateurs ont pour objectif la mise à disposition des services de la Plateforme, leur amélioration et le maintien d&#x27;un environnement sécurisé. La base légale des traitements est l’exécution du contrat entre l’utilisateur et la Plateforme. Plus précisément, les utilisations sont les suivantes :- accès et utilisation de la Plateforme par l&#x27;utilisateur ;<br></br>- gestion du fonctionnement et optimisation de la Plateforme ;<br></br>- mise en œuvre d&#x27;une assistance utilisateurs ;<br></br>- vérification, identification et authentification des données transmises par l&#x27;utilisateur ;<br></br>- personnalisation des services en affichant des publicités en fonction de l&#x27;historique de navigation de l&#x27;utilisateur, selon ses préférences ;<br></br>- prévention et détection des fraudes, malwares (malicious softwares ou logiciels malveillants) et gestion des incidents de sécurité ;<br></br>- gestion des éventuels litiges avec les utilisateurs ;<br></br>- envoi d&#x27;informations commerciales et publicitaires, en fonction des préférences de l&#x27;utilisateur ;<br></br></p>
  <h4 class="heading-43"><strong class="bold-text-10">Article 10 - Politique de conservation des données</strong></h4>
  <p class="paragraph-32">La Plateforme conserve vos données pour la durée nécessaire pour vous fournir ses services ou<br></br>son assistance.<br></br>Dans la mesure raisonnablement nécessaire ou requise pour satisfaire aux obligations légales ou réglementaires, régler des litiges, empêcher les fraudes et abus ou appliquer nos modalités et conditions, nous pouvons également conserver certaines de vos informations si nécessaire, même après que vous ayez fermé votre compte ou que nous n&#x27;ayons plus besoin pour vous fournir nos services.<br></br></p>
  <h4 class="heading-43"><strong class="bold-text-10">Article 11 - Partage des données personnelles avec des tiers</strong></h4>
  <p class="paragraph-32">Les données personnelles peuvent être partagées avec des sociétés tierces exclusivement dans l’Union européenne, dans les cas suivants :<br></br>- lorsque l&#x27;utilisateur publie, dans les zones de commentaires libres de la Plateforme, des informations accessibles au public ;- quand l&#x27;utilisateur autorise le site web d&#x27;un tiers à accéder à ses données ;<br></br>- quand la Plateforme recourt aux services de prestataires pour fournir l&#x27;assistance utilisateurs, la publicité et les services de paiement. Ces prestataires disposent d&#x27;un accès limité aux données de l&#x27;utilisateur, dans le cadre de l&#x27;exécution de ces prestations, et ont l&#x27;obligation contractuelle de les utiliser en conformité avec les dispositions de la réglementation applicable en matière protection des données à caractère personnel ;<br></br>- si la loi l&#x27;exige, la Plateforme peut effectuer la transmission de données pour donner suite aux réclamations présentées contre la Plateforme et se conformer aux procédures administratives et judiciaires.<br></br></p>
  <h4 class="heading-43"><strong class="bold-text-10">Article 12 - Offres commerciales</strong></h4>
  <p class="paragraph-32">Vous êtes susceptible de recevoir des offres commerciales de l&#x27;éditeur. Si vous ne le souhaitez pas, veuillez cliquer sur le lien suivant : hello@kerudao.org.<br></br>Vos données sont susceptibles d’être utilisées par les partenaires de l&#x27;éditeur à des fins de prospection commerciale, si vous ne le souhaitez pas, veuillez cliquer sur le lien suivant : hello@kerudao.org.Si, lors de la consultation du site, vous accédez à des données à caractère personnel, vous devez vous abstenir de toute collecte, de toute utilisation non autorisée et de tout acte pouvant constituer une atteinte à la vie privée ou à la réputation des personnes. L&#x27;éditeur décline toute responsabilité à cet égard.<br></br>Les données sont conservées et utilisées pour une durée conforme à la législation en vigueur.<br></br></p>
  <h4 class="heading-43"><strong class="bold-text-10">Article 13 - Cookies</strong></h4>
  <p class="paragraph-32">Qu’est-ce qu’un « cookie » ?Un « Cookie » ou traceur est un fichier électronique déposé sur un terminal (ordinateur, tablette, smartphone,...) et lu par exemple lors de la consultation d&#x27;un site internet, de la lecture d&#x27;un courrier électronique, del&#x27;installation ou de l&#x27;utilisation d&#x27;un logiciel ou d&#x27;une application mobile et ce, quel que soit le type determinal utilisé (source : https://www.cnil.fr/fr/cookies-traceurs-que-dit-la-loi).<br></br>Le site peut collecter automatiquement des informations standards. Toutes les informations collectées indirectement neseront utilisées que pour suivre le volume, le type et la configuration du trafic utilisant ce site, pour en développer la conception et l&#x27;agencement et à d&#x27;autres fins administratives et de planification et plus généralement pour améliorer le service que nous vous offrons.<br></br>Le cas échéant, des « cookies » émanant de l&#x27;éditeur du site et/ou des sociétés tiers pourront être déposés sur votre terminal, avec votre accord. Dans ce cas, lors de la première navigation sur ce site, une bannière explicative sur l’utilisation des « cookies » apparaîtra. Avant de poursuivre la navigation, le client et/ou le prospect devra accepter ou refuser l’utilisation desdits « cookies ». Le consentement donné sera valable pour une période de treize (13) mois. L&#x27;utilisateur a la possibilité de désactiver les cookies à tout moment.<br></br>Les cookies suivants sont présents sur ce site :<strong>Cookies Google :</strong>- Google analytics : permet de mesurer l&#x27;audience du site ;<br></br>- Google tag manager : facilite l’implémentation des tags sur les pages et permet de gérer les balises Google ; - Google Adsense : régie publicitaire de Google utilisant les sites web ou les vidéos YouTube comme support pour ses annonces ;<br></br>- Google Dynamic Remarketing : permet de vous proposer de la publicité dynamique en fonction des précédentes recherches ;<br></br>- Google Adwords Conversion : outil de suivi des campagnes publicitaires adwords ;<br></br>- DoubleClick : cookies publicitaires de Google pour diffuser des bannières.<br></br>La durée de vie de ces cookies est de treize mois.<br></br></p>
  <h4 class="heading-43"><strong class="bold-text-10">Article 14 - Photographies et représentation des produits</strong></h4>
  <p class="paragraph-32">Les photographies de produits, accompagnant leur description, ne sont pas contractuelles et n&#x27;engagent pas l&#x27;éditeur.<br></br></p>
  <h4 class="heading-43"><strong class="bold-text-10">Article 15 - Loi applicable</strong></h4>
  <p class="paragraph-32">Les présentes conditions d&#x27;utilisation du site sont régies par la loi française et soumises à la compétence destribunaux du siège social de l&#x27;éditeur, sous réserve d&#x27;une attribution de compétence spécifique découlant d&#x27;un texte de loi ou réglementaire particulier.<br></br></p>
  <h4 class="heading-43"><strong class="bold-text-10">Article 16 - Contactez-nous</strong></h4>
  <p class="paragraph-32">Pour toute question, information sur les produits présentés sur le site, ou concernant le site lui-même, vous pouvez laisser un message à l&#x27;adresse suivante : hello@kerudao.org.<br></br></p>
  </div>
  </body>
  </div>
  );
}